@token = {{$dotenv TOKEN}}

### Is Running
GET https://git.nevenall.games?token={{token}}


### GET common compendiums 
GET https://git.nevenall.games/foundry-common-compendiums/module.json?token={{token}} HTTP/1.1


### GET warhammer40k
GET https://git.nevenall.games/foundry-warhammer40k/system.json?token={{token}} HTTP/1.1


### GET archive from local
GET https://git.nevenall.games/foundry-warhammer40k/master.zip?token={{token}} HTTP/1.1

### online?
GET https://git.nevenall.games?token={{token}}


### GET ​— online app
GET https://private-repository-access-9ylf6.ondigitalocean.app/foundry-warhammer40k/system.json?token={{token}} HTTP/1.1


### OPTIONS ​— online app
OPTIONS https://private-repository-access-9ylf6.ondigitalocean.app/foundry-warhammer40k/system.json?token={{token}} HTTP/1.1